db:
  user: kemal
  password: kemalpassword
  db: invidious
  host: db
  port: 5432
  dbname: invidious-db

check_tables: true
domain: invidious-latest-nni3.onrender.com
http_port: 3000
external_port: 3000
host_binding: 0.0.0.0
https_only: false
unencrypted_video_proxy: true
captcha_enabled: false
hmac_key: "2b91e7005c1e8ce4df8c246f2556da0a21e22e0b49ba21ded2d92bd28eb438ff"
invidious_companion:
  - private_url: "http://invidious-latest-nni3.onrender.com:8282/companion"
    invidious_companion_key: "d0addeadda05179c"

default_user_preferences:
  video_loop: false
  autoplay: false
  continue: false
  listen: false
  quality: "dash"
  quality_dash: "240p"
